spring:
  application:
    name: hrpayroll
  datasource:
    username: thongfazon
    password: itp@168
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5169/share_db

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
